# Generated by Django 4.2.10 on 2024-03-25 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bank', models.CharField(max_length=100, unique=True, verbose_name='Название банка')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='TypeBankAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type_bank_acc', models.CharField(max_length=100, unique=True, verbose_name='Название типа счета')),
            ],
        ),
        migrations.CreateModel(
            name='TypesCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, unique=True, verbose_name='Название типа категории')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sub_cat', models.CharField(max_length=100, verbose_name='Название подкатегории')),
                ('id_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazmasterapp.categories', verbose_name='Название категории')),
            ],
        ),
        migrations.AddField(
            model_name='categories',
            name='id_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazmasterapp.typescategories', verbose_name='Название типа категории'),
        ),
        migrations.CreateModel(
            name='BankAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bank_acc', models.CharField(max_length=100, verbose_name='Название счета')),
                ('summary', models.FloatField(verbose_name='Сумма')),
                ('create_date', models.DateField(verbose_name='Дата создания')),
                ('close_date', models.DateField(verbose_name='Дата закрытия')),
                ('isActive', models.BooleanField(verbose_name='Активен')),
                ('id_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazmasterapp.bank', verbose_name='Название банка')),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bazmasterapp.typebankaccounts', verbose_name='Название типа счета')),
            ],
        ),
    ]
